name       : python-cssselect
version    : 1.1.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/70/54/37630f6eb2c214cdee2ae56b7287394c8aa2f3bafb8b4eb8c3791aae7a14/cssselect-1.1.0.tar.gz : f95f8dedd925fd8f54edb3d2dfb44c190d9d18512377d3c1e2388d16126879bc
license    : BSD-3-Clause
component  : programming.python
summary    : cssselect parses CSS3 Selectors and translates them to XPath 1.0
description: |
    cssselect parses CSS3 Selectors and translate them to XPath 1.0 expressions. Such expressions can be used in lxml or another XPath engine to find the matching elements in an XML or HTML document.
build      : |
    %python3_setup
install    : |
    %python3_install
