name       : python-cssselect
version    : 1.2.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/c/cssselect/cssselect-1.2.0.tar.gz : 666b19839cfaddb9ce9d36bfe4c969132c647b92fc9088c4e23f786b30f1b3dc
homepage   : https://github.com/scrapy/cssselect
license    : BSD-3-Clause
component  : programming.python
summary    : cssselect parses CSS3 Selectors and translates them to XPath 1.0
description: |
    cssselect parses CSS3 Selectors and translate them to XPath 1.0 expressions. Such expressions can be used in lxml or another XPath engine to find the matching elements in an XML or HTML document.
builddeps  :
    - python-lxml   # check
    - python-pytest # check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
