name       : python-cssselect
version    : 0.9.1
release    : 1
source     :
    - https://pypi.python.org/packages/source/c/cssselect/cssselect-0.9.1.tar.gz : 0535a7e27014874b27ae3a4d33e8749e345bdfa62766195208b7996bf1100682
license    : BSD-3-Clause
summary    : cssselect parses CSS3 Selectors and translates them to XPath 1.0
description: |
    cssselect parses CSS3 Selectors and translate them to XPath 1.0 expressions. Such expressions can be used in lxml or another XPath engine to find the matching elements in an XML or HTML document.
builddeps  :
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
